# Generated by Django 6.0.2 on 2026-02-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('alecodigo', models.BigAutoField(db_column='alecodigo', primary_key=True, serialize=False)),
                ('aletipo', models.CharField(db_column='aletipo', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('ingcodigo', models.BigAutoField(db_column='ingcodigo', primary_key=True, serialize=False)),
                ('ingtipo', models.CharField(db_column='ingtipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('nutcodigo', models.BigAutoField(db_column='nutcodigo', primary_key=True, serialize=False)),
                ('nutemail', models.EmailField(db_column='nutemail', max_length=254)),
                ('nutsenha', models.CharField(db_column='nutsenha')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('paicodigo', models.BigAutoField(db_column='paicodigo', primary_key=True, serialize=False)),
                ('painome', models.CharField(db_column='painome')),
                ('paiemail', models.EmailField(db_column='paiemail', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('alucodigo', models.BigAutoField(db_column='alucodigo', primary_key=True, serialize=False)),
                ('alunome', models.CharField(db_column='alunome', max_length=60)),
                ('aluemail', models.EmailField(db_column='aluemail', max_length=254)),
                ('alusenha', models.CharField(db_column='alusenha', max_length=60)),
                ('alumatricula', models.CharField(db_column='alumatricula', max_length=60)),
                ('alupaicodigo', models.ForeignKey(db_column='alupaicodigo', on_delete=django.db.models.deletion.CASCADE, to='merenda_app.pais')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('refcodigo', models.BigAutoField(db_column='refcodigo', primary_key=True, serialize=False)),
                ('refnome', models.CharField(db_column='refnome', max_length=60)),
                ('refproteina', models.IntegerField(db_column='refproteina')),
                ('refcarboidrato', models.IntegerField(db_column='refcarboidrato')),
                ('refcalorias', models.IntegerField(db_column='refcalorias')),
                ('refnutcodigo', models.ForeignKey(db_column='refnutcodigo', on_delete=django.db.models.deletion.CASCADE, to='merenda_app.nutricionista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('carcodigo', models.BigAutoField(db_column='carcodigo', primary_key=True, serialize=False)),
                ('cardata', models.DateTimeField(db_column='cardata')),
                ('carrefcodigo', models.ForeignKey(db_column='carrefcodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.refeicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertaLog',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('logcodigo', models.BigAutoField(db_column='logcodigo', primary_key=True, serialize=False)),
                ('logvisualizacao', models.BooleanField(db_column='logvisualizacao', default=False, null=True)),
                ('logalecodigo', models.ForeignKey(db_column='logalecodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.alergia')),
                ('logalunocodigo', models.ForeignKey(db_column='logalunocodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.aluno')),
                ('logrefcodigo', models.ForeignKey(db_column='logrefcodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.refeicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refeicao_Ingrediente',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('refingcodigo', models.BigAutoField(db_column='refingcodigo', primary_key=True, serialize=False)),
                ('refingingcodigo', models.ForeignKey(db_column='refing_ingcodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.ingrediente')),
                ('refingrefcodigo', models.ForeignKey(db_column='refing_refcodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.refeicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='refeicao',
            name='refingredientes',
            field=models.ManyToManyField(through='merenda_app.Refeicao_Ingrediente', to='merenda_app.ingrediente'),
        ),
        migrations.CreateModel(
            name='Restricoes_alimentares',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('resali_codigo', models.BigAutoField(db_column='resali_codigo', primary_key=True, serialize=False)),
                ('resali_alucodigo', models.ForeignKey(db_column='resali_alecodigo', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_restritos', to='merenda_app.alergia')),
                ('resali_ingcodigo', models.ForeignKey(db_column='resali_ingcodigo', on_delete=django.db.models.deletion.CASCADE, to='merenda_app.ingrediente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alergia',
            name='restricoes_alimentares',
            field=models.ManyToManyField(through='merenda_app.Restricoes_alimentares', to='merenda_app.ingrediente'),
        ),
        migrations.CreateModel(
            name='Restricoes_Alunos',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('resalu_codigo', models.BigAutoField(db_column='resalu_codigo', primary_key=True, serialize=False)),
                ('resalu_alecodigo', models.ForeignKey(db_column='resalu_alecodigo', on_delete=django.db.models.deletion.PROTECT, related_name='aluno_restricao', to='merenda_app.alergia')),
                ('resalu_alucodigo', models.ForeignKey(db_column='resalu_alucodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alergia',
            name='restricoes_alunos',
            field=models.ManyToManyField(through='merenda_app.Restricoes_Alunos', to='merenda_app.aluno'),
        ),
    ]
