# Generated by Django 6.0.2 on 2026-02-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='paisenha',
            field=models.CharField(db_column='paisenha', default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='alusenha',
            field=models.CharField(db_column='alusenha', max_length=255),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='nutsenha',
            field=models.CharField(db_column='nutsenha', max_length=255),
        ),
    ]
