# Generated by Django 6.0.2 on 2026-02-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda_app', '0002_pais_paisenha_alter_aluno_alusenha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restricoes_alimentares',
            old_name='resali_alucodigo',
            new_name='resali_alicodigo',
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='nutnome',
            field=models.CharField(db_column='nutnome', default=3, max_length=60),
            preserve_default=False,
        ),
    ]
