# Generated by Django 6.0.2 on 2026-02-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda_app', '0003_rename_resali_alucodigo_restricoes_alimentares_resali_alicodigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='carrefcodigo',
        ),
        migrations.CreateModel(
            name='Cardapio_refeicao',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('carrefcodigo', models.BigAutoField(db_column='carrefcodigo', primary_key=True, serialize=False)),
                ('carref_carcodigo', models.ForeignKey(db_column='carref_carcodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.cardapio')),
                ('carref_refcodigo', models.ForeignKey(db_column='carref_refcodigo', on_delete=django.db.models.deletion.PROTECT, to='merenda_app.refeicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cardapio',
            name='carrefeicoes',
            field=models.ManyToManyField(through='merenda_app.Cardapio_refeicao', to='merenda_app.refeicao'),
        ),
    ]
