# Generated by Django 6.0.2 on 2026-02-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda_app', '0004_remove_cardapio_carrefcodigo_cardapio_refeicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='alucpf',
            field=models.CharField(db_column='alucpf', default=4, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='nutcpf',
            field=models.CharField(db_column='nutcpf', default=5, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='paicpf',
            field=models.CharField(db_column='paicpf', default=6, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
