# Generated by Django 6.0.2 on 2026-02-27 00:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda_app', '0005_aluno_alucpf_nutricionista_nutcpf_pais_paicpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricionista',
            name='nutcpf',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='alucpf',
            field=models.CharField(db_column='alucpf', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='alupaicodigo',
            field=models.ForeignKey(blank=True, db_column='alupaicodigo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='merenda_app.pais'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='paicpf',
            field=models.CharField(db_column='paicpf', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
    ]
