# Generated by Django 6.0.2 on 2026-02-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda_app', '0006_remove_nutricionista_nutcpf_alter_aluno_alucpf_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='aluno',
                    name='aluidade',
                    field=models.IntegerField(db_column='aluidade', default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='refeicao',
            name='refalergias',
            field=models.ManyToManyField(blank=True, related_name='refeicoes', to='merenda_app.alergia'),
        ),
        migrations.AddField(
            model_name='refeicao',
            name='refimagem',
            field=models.ImageField(blank=True, db_column='refimagem', null=True, upload_to='refeicoes/'),
        ),
    ]
